### ISSUE TITLE
Regarding Reinforcement Learning

### ISSUE THREAD

**Issue by ghost** [soumik12345/Twin-Delayed-DDPG#1]
.

**Comment by soumik12345** [comment]
@deepseek 
In order to solve a problem, you need to first frame the problem. The best way to start would be to create a gym environment out of that. As for the solution, the problem certainly is not a continuous control problem, so you can avoid DDPG or TD3. Start benchmarking your environment with vanilla Q-learning and move to other methods. Hope that helps :)
